version: '3.3'
name: multidirectory
services:
  interface:
    container_name: interface
    build:
      context: ./
      dockerfile: configurations/docker/Dockerfile.dev
    restart: 'no'
    hostname: interface
    environment:
      API_URL: http://md.localhost/api
    ports:
      - 9080:80
    working_dir: /app
    volumes:
      - '.:/app'
      - '/app/node_modules'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.interface.rule=Host(`md.localhost`)'
      - 'traefik.http.routers.interface.entrypoints=web'
      - 'traefik.http.services.interface.loadbalancer.server.port=80'
    command: bash -c '
      sed "s,[$]{API_URL},"$$API_URL",g" /app/projects/multidirectory-app/src/assets/env.template.js > /app/projects/multidirectory-app/src/assets/env.js &&
      ng serve --host 0.0.0.0 --port 80 --poll 2000'

  multidirectory-storybook:
    build:
      context: .
      dockerfile: Dockerfile.storybook
    restart: always
    profiles:
      - showcase
    ports:
      - 9081:80
    container_name: multidirectory-ui-storybook

volumes:
  node_modules:
