version: '3.3'
name: multidirectory
services:
  interface:
    container_name: interface
    build:
      context: ./
      dockerfile: configurations/docker/Dockerfile.dev
      args:
        - API_URL=http://md.localhost/api
    restart: 'no'
    hostname: interface
    environment:
      - HUSKY=0
      - NODE_ENV=development
    ports:
      - 9080:80
    working_dir: /app
    volumes:
      - '.:/app'
      - '/app/node_modules'
      - '/app/projects/multidirectory-app/src/assets'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.interface.rule=Host(`md.localhost`)'
      - 'traefik.http.routers.interface.entrypoints=web'
      - 'traefik.http.services.interface.loadbalancer.server.port=80'
    command: ng serve --host 0.0.0.0 --port 80 --poll 2000

  multidirectory-storybook:
    build:
      context: .
      dockerfile: Dockerfile.storybook
    restart: always
    profiles:
      - showcase
    ports:
      - 9081:80
    container_name: multidirectory-ui-storybook

volumes:
  node_modules:
