FROM node:18.16.0 as build
RUN npm install -g @angular/cli@14.1.0
WORKDIR /app
COPY package.json /app/package.json
RUN npm install
COPY . /app
RUN ng build multidirectory-ui-kit
RUN npm link dist/multidirectory-ui-kit/
RUN npm run build-storybook
COPY . /app
EXPOSE 3000
FROM nginx:1.17.1-alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build  /app/storybook-static/. /usr/share/nginx/html/.
