FROM node:18 
RUN yarn config set registry https://registry.npmjs.org/ && \
    yarn global add @angular/cli@18
COPY package.json /app/package.json
WORKDIR /app
RUN yarn install --no-audit
RUN ng build multidirectory-ui-kit && \
    npm link dist/multidirectory-ui-kit/
