FROM node:22 as base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
COPY . /app
WORKDIR /app

FROM base AS prod-deps
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --prod --frozen-lockfile

FROM base AS build
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN pnpm run build

FROM base

WORKDIR /app
COPY package.json /app/package.json
COPY . /app
RUN pnpm install -g @angular/cli@18 &&\
    pnpm install &&\
    ng build multidirectory-ui-kit &&\
    pnpm add file:dist/multidirectory-ui-kit/

RUN ng build multidirectory-ui-kit --watch &