export enum DnsRuleType {
  A = 'A',
  AAAA = 'AAAA',
  PTR = 'PTR',
  CNAME = 'CNAME',
  ANAME = 'ANAME',
  TXT = 'TXT',
  MX = 'MX',
  SRV = 'SRV',
  NS = 'NS',
  CAA = 'CAA',
  SOA = 'SOA',
  SVCB = 'SVCB',
  HTTPS = 'HTTPS',
}
